### PR TITLE
Configuration should use rootNode to avoid deprecations on symfony v4.3

### PR DESCRIPTION
**Pull request by PWalkow**
Fixing the deprecation issue from #32

### CODE REVIEW

**Comment by Nightbr** [comment]
Hey, 
thanks for your contribution 🎉 

Your PR is great but it seems that Travis has hard time with the PHP 5.6 build (memory overflow with composer...). 

Seems there is a lot of problem with memory, composer & php 5.6... (see #31) I will drop the support of php 5.6 later I think but right now can you try modifying the .travis.yml with:

```
before_script:
    - php -dmemory_limit=-1 composer install --dev -v --prefer-source
```

In order to fix the memory problem with Travis... Not very clean but a quick fix for now.

**Other leads to quick fix the memory problem:**
- https://github.com/geerlingguy/drupal-vm/commit/dde3e73e3c5b38a20e1037bba79aae29ddeab5b3
- https://stackoverflow.com/questions/51341463/unable-to-change-travis-ci-php-memory-limit/51381888

**Comment by florianajir** [comment]
any news on this ?

**Comment by laurent-bientz** [comment]
ping @Nightbr can we merge this one? can't migrate to symfony 5 because of this.

**Comment by Nightbr** [comment]
The pipeline still failed so I cannot approved and merge this. Feel free to update or open a new PR. 

Another thing, If someone who use this on daily basis want to become a maintainer, I can grant you, just ask for it in a conversation or an issue.

**Comment by Nightbr** [comment]
Add to that, I think the best thing is to drop php5.6 and move to Symfony 3 min and publish a 2.0.0 package, see this issue https://github.com/welpdev/mailchimp-bundle/issues/31

**Comment by Nightbr** [comment]
Fixed in [`1.3.2`](https://github.com/welpdev/mailchimp-bundle/releases/tag/1.3.2)

**Pull request closed without merging**
