### PR TITLE
Commands tagged and services made public in order to work on Symfony 4

### PR DESCRIPTION
**Pull request by pcmsystemsltd**

### CODE REVIEW

**Comment by jeroendk** [comment]
@piermont Why do the services need to be public  ?

**Comment by pcmsystemsltd** [comment]
Symfony 4 changes services slightly. If they are not public the following exception is thrown.

```The "welp_mailchimp.list_provider" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.  "```

**Comment by Nightbr** [comment]
You can use dependency injection with type hinting to inject the class/service needed. In SF4, you don't access service through the container.

**Comment by pcmsystemsltd** [comment]
Do you prefer to inject them so they are no longer public?

**Comment by Nightbr** [comment]
I think we should rework a little this Bundle to be Symfony 4 compliant and use the DI properly.

ok for console command.

**Comment by pcmsystemsltd** [comment]
We needed it to work in our Symfony 4 projects, it's not ideal but it makes it usable.

Thanks for your work guys!

**Comment by Nightbr** [comment]
lets merge this to be usable for Symfony 4 but we really need a rewrite in order to use the DI properly...

**Pull request merged**
